[project]
name = "pyscope"
version = "0.1.0"
description = "A python-based API for gradescope"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4",
    "requests",
    "click",
]
